#include "DrumKitLibrary.h"
#include <algorithm>

static std::vector<DrumKitDefinition> buildAllKits()
{
    return {
    { "generic_controller_generic_no_cc", "Generic (No CC)", "Generic Controller", {
        { 36, "Kick", "Head" },
        { 35, "Kick 2", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 48, "Tom 1", "Head" },
        { 47, "Tom 2", "Head" },
        { 43, "Tom 3", "Head" },
        { 41, "Tom 4", "Head" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 59, "Ride", "Edge" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
        { 57, "Crash 2", "Bow" },
        { 52, "Crash 2", "Edge" },
        { 27, "Crash 3", "Bow" },
        { 28, "Crash 3", "Edge" },
        { 29, "Crash 4", "Bow" },
        { 30, "Crash 4", "Edge" },
    }, 4 },
    { "generic_controller_generic_cc_hi_hat", "Generic (CC Hi-Hat)", "Generic Controller", {
        { 36, "Kick", "Head" },
        { 35, "Kick 2", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 14, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 18, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 20, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 24, "Tom 4", "Head" },
        { 39, "Tom 4", "Rim" },
        { 11, "Hi-Hat", "Closed" },
        { 12, "Hi-Hat", "Open" },
        { 22, "HH Edge", "Closed" },
        { 26, "HH Edge", "Open" },
        { 21, "HH Pedal", "Chick" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 59, "Ride", "Edge" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
        { 57, "Crash 2", "Bow" },
        { 52, "Crash 2", "Edge" },
        { 27, "Crash 3", "Bow" },
        { 28, "Crash 3", "Edge" },
        { 29, "Crash 4", "Bow" },
        { 30, "Crash 4", "Edge" },
        { 31, "Crash 5", "Bow" },
        { 32, "Crash 5", "Edge" },
    }, 4 },
    { "2box_drumit_three", "Drumit Three", "2box", {
        { 36, "Kick", "Head" },
        { 41, "Snare", "Head" },
        { 42, "Snare", "Rimshot" },
        { 50, "Tom 1", "Head" },
        { 51, "Tom 1", "Rim" },
        { 53, "Tom 2", "Head" },
        { 54, "Tom 2", "Rim" },
        { 57, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 60, "Tom 4", "Head" },
        { 61, "Tom 4", "Rim" },
        { 45, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 47, "HH Pedal", "Chick" },
        { 71, "Ride", "Bell" },
        { 72, "Ride", "Bow" },
        { 73, "Ride", "Edge" },
        { 65, "Crash 1", "Bow" },
        { 64, "Crash 1", "Bell" },
        { 66, "Crash 1", "Edge" },
        { 77, "Crash 2", "Bow" },
        { 76, "Crash 2", "Bell" },
        { 78, "Crash 2", "Edge" },
    }, 4 },
    { "2box_drumit_five", "Drumit Five", "2box", {
        { 36, "Kick", "Head" },
        { 41, "Snare", "Head" },
        { 42, "Snare", "Rimshot" },
        { 50, "Tom 1", "Head" },
        { 51, "Tom 1", "Rim" },
        { 53, "Tom 2", "Head" },
        { 54, "Tom 2", "Rim" },
        { 57, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 60, "Tom 4", "Head" },
        { 61, "Tom 4", "Rim" },
        { 45, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 47, "HH Pedal", "Chick" },
        { 71, "Ride", "Bell" },
        { 72, "Ride", "Bow" },
        { 73, "Ride", "Edge" },
        { 65, "Crash 1", "Bow" },
        { 64, "Crash 1", "Bell" },
        { 66, "Crash 1", "Edge" },
        { 77, "Crash 2", "Bow" },
        { 76, "Crash 2", "Bell" },
        { 78, "Crash 2", "Edge" },
    }, 4 },
    { "2box_speedlight_kit", "Speedlight Kit", "2box", {
        { 36, "Kick", "Head" },
        { 41, "Snare", "Head" },
        { 42, "Snare", "Rimshot" },
        { 50, "Tom 1", "Head" },
        { 51, "Tom 1", "Rim" },
        { 53, "Tom 2", "Head" },
        { 54, "Tom 2", "Rim" },
        { 57, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 60, "Tom 4", "Head" },
        { 61, "Tom 4", "Rim" },
        { 45, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 47, "HH Pedal", "Chick" },
        { 71, "Ride", "Bell" },
        { 72, "Ride", "Bow" },
        { 73, "Ride", "Edge" },
        { 65, "Crash 1", "Bow" },
        { 64, "Crash 1", "Bell" },
        { 66, "Crash 1", "Edge" },
        { 77, "Crash 2", "Bow" },
        { 76, "Crash 2", "Bell" },
        { 78, "Crash 2", "Edge" },
    }, 4 },
    { "alesis_dm_5", "DM-5", "Alesis", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 48, "Tom 1", "Head" },
        { 45, "Tom 2", "Head" },
        { 41, "Tom 3", "Head" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 51, "Ride", "Bow" },
        { 49, "Crash 1", "Edge" },
        { 57, "Crash 2", "Edge" },
    }, 3 },
    { "alesis_dm_10", "DM-10", "Alesis", {
        { 36, "Kick", "Head" },
        { 35, "Kick 2", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 47, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 48, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 41, "Tom 3", "Rim" },
        { 63, "Tom 4", "Head" },
        { 64, "Tom 4", "Rim" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 31, "HH Edge", "Closed" },
        { 32, "HH Edge", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 30, "HH Pedal", "Splash" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 59, "Ride", "Edge" },
        { 49, "Crash 1", "Edge" },
        { 57, "Crash 2", "Edge" },
        { 60, "Crash 3", "Edge" },
        { 28, "Crash 4", "Edge" },
    }, 4 },
    { "alesis_command", "Command", "Alesis", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 41, "Tom 4", "Head" },
        { 39, "Tom 4", "Rim" },
        { 42, "HH Edge", "Closed" },
        { 46, "HH Edge", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 21, "HH Pedal", "Splash" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 59, "Ride", "Edge" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
        { 57, "Crash 2", "Bow" },
        { 52, "Crash 2", "Edge" },
    }, 4 },
    { "alesis_crimson", "Crimson", "Alesis", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 41, "Tom 4", "Head" },
        { 39, "Tom 4", "Rim" },
        { 42, "HH Edge", "Closed" },
        { 46, "HH Edge", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 21, "HH Pedal", "Splash" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 59, "Ride", "Edge" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
        { 57, "Crash 2", "Bow" },
        { 52, "Crash 2", "Edge" },
    }, 4 },
    { "alesis_forge", "Forge", "Alesis", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 41, "Tom 4", "Head" },
        { 39, "Tom 4", "Rim" },
        { 42, "HH Edge", "Closed" },
        { 46, "HH Edge", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 21, "HH Pedal", "Splash" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 59, "Ride", "Edge" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
        { 57, "Crash 2", "Bow" },
        { 52, "Crash 2", "Edge" },
    }, 4 },
    { "alesis_nitro", "Nitro", "Alesis", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 41, "Tom 4", "Head" },
        { 39, "Tom 4", "Rim" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 23, "Hi-Hat", "Half Open" },
        { 44, "HH Pedal", "Chick" },
        { 21, "HH Pedal", "Splash" },
        { 51, "Ride", "Bow" },
        { 49, "Crash 1", "Edge" },
        { 57, "Crash 2", "Edge" },
    }, 4 },
    { "alesis_strata_core", "Strata Core", "Alesis", {
        { 24, "Kick", "Head" },
        { 26, "Snare", "Head" },
        { 29, "Snare", "Rimshot" },
        { 25, "Snare", "X-Stick" },
        { 38, "Tom 1", "Head" },
        { 70, "Tom 1", "Rim" },
        { 35, "Tom 2", "Head" },
        { 66, "Tom 2", "Rim" },
        { 31, "Tom 3", "Head" },
        { 61, "Tom 3", "Rim" },
        { 18, "Hi-Hat", "Closed" },
        { 20, "HH Edge", "Closed" },
        { 32, "HH Pedal", "Chick" },
        { 22, "HH Bell", "Closed" },
        { 60, "Ride", "Bow" },
        { 71, "Ride", "Bell" },
        { 50, "Ride", "Edge" },
        { 52, "Crash 1", "Bow" },
        { 41, "Crash 1", "Edge" },
        { 62, "Crash 1", "Bell" },
        { 55, "Crash 2", "Bow" },
        { 45, "Crash 2", "Edge" },
        { 65, "Crash 2", "Bell" },
        { 53, "Crash 3", "Bow" },
        { 43, "Crash 3", "Edge" },
        { 64, "Crash 3", "Bell" },
    }, 4 },
    { "alesis_strata_prime", "Strata Prime", "Alesis", {
        { 24, "Kick", "Head" },
        { 26, "Snare", "Head" },
        { 29, "Snare", "Rimshot" },
        { 25, "Snare", "X-Stick" },
        { 38, "Tom 1", "Head" },
        { 70, "Tom 1", "Rim" },
        { 35, "Tom 2", "Head" },
        { 66, "Tom 2", "Rim" },
        { 31, "Tom 3", "Head" },
        { 61, "Tom 3", "Rim" },
        { 33, "Tom 4", "Head" },
        { 63, "Tom 4", "Rim" },
        { 18, "Hi-Hat", "Closed" },
        { 20, "HH Edge", "Closed" },
        { 32, "HH Pedal", "Chick" },
        { 22, "HH Bell", "Closed" },
        { 60, "Ride", "Bow" },
        { 71, "Ride", "Bell" },
        { 50, "Ride", "Edge" },
        { 52, "Crash 1", "Bow" },
        { 41, "Crash 1", "Edge" },
        { 62, "Crash 1", "Bell" },
        { 55, "Crash 2", "Bow" },
        { 45, "Crash 2", "Edge" },
        { 65, "Crash 2", "Bell" },
        { 53, "Crash 3", "Bow" },
        { 43, "Crash 3", "Edge" },
        { 64, "Crash 3", "Bell" },
        { 57, "Crash 4", "Bow" },
        { 47, "Crash 4", "Edge" },
        { 67, "Crash 4", "Bell" },
    }, 4 },
    { "alesis_strike", "Strike", "Alesis", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 50, "Tom 1", "Head" },
        { 82, "Tom 1", "Rim" },
        { 47, "Tom 2", "Head" },
        { 80, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 75, "Tom 3", "Rim" },
        { 41, "Tom 4", "Head" },
        { 73, "Tom 4", "Rim" },
        { 8, "Hi-Hat", "Closed" },
        { 7, "HH Edge", "Closed" },
        { 22, "HH Pedal", "Chick" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 59, "Ride", "Edge" },
        { 48, "Crash 1", "Bow" },
        { 49, "Crash 1", "Edge" },
        { 60, "Crash 2", "Bow" },
        { 57, "Crash 2", "Edge" },
        { 28, "Crash 3", "Bow" },
        { 55, "Crash 3", "Edge" },
    }, 4 },
    { "alesis_strike_pro", "Strike Pro", "Alesis", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 50, "Tom 1", "Head" },
        { 82, "Tom 1", "Rim" },
        { 47, "Tom 2", "Head" },
        { 80, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 75, "Tom 3", "Rim" },
        { 41, "Tom 4", "Head" },
        { 73, "Tom 4", "Rim" },
        { 8, "Hi-Hat", "Closed" },
        { 7, "HH Edge", "Closed" },
        { 22, "HH Pedal", "Chick" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 59, "Ride", "Edge" },
        { 48, "Crash 1", "Bow" },
        { 49, "Crash 1", "Edge" },
        { 60, "Crash 2", "Bow" },
        { 57, "Crash 2", "Edge" },
        { 28, "Crash 3", "Bow" },
        { 55, "Crash 3", "Edge" },
    }, 4 },
    { "alesis_surge", "Surge", "Alesis", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 41, "Tom 4", "Head" },
        { 39, "Tom 4", "Rim" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 23, "Hi-Hat", "Half Open" },
        { 44, "HH Pedal", "Chick" },
        { 21, "HH Pedal", "Splash" },
        { 51, "Ride", "Bow" },
        { 49, "Crash 1", "Edge" },
        { 57, "Crash 2", "Edge" },
    }, 4 },
    { "ddrum_ddti", "DDTi", "ddrum", {
        { 35, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 47, "Tom 1", "Head" },
        { 45, "Tom 2", "Head" },
        { 43, "Tom 3", "Head" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 55, "Ride", "Bow" },
        { 54, "Ride", "Edge" },
        { 49, "Crash 1", "Bow" },
        { 58, "Crash 1", "Edge" },
        { 53, "Crash 2", "Bow" },
    }, 4 },
    { "drum_workshop_dwe", "DWe", "Drum Workshop", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 71, "Tom 1", "Head" },
        { 73, "Tom 1", "Rim" },
        { 72, "Tom 1", "Rim FX" },
        { 48, "Tom 2", "Head" },
        { 50, "Tom 2", "Rim" },
        { 5, "Tom 2", "Rim FX" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 7, "Tom 3", "Rim FX" },
        { 41, "Tom 4", "Head" },
        { 39, "Tom 4", "Rim" },
        { 8, "Tom 4", "Rim FX" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 22, "HH Edge", "Closed" },
        { 26, "HH Edge", "Open" },
        { 93, "HH Bell", "Closed" },
        { 44, "HH Pedal", "Chick" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 59, "Ride", "Edge" },
        { 25, "Ride", "Mute" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
        { 95, "Crash 1", "Bell" },
        { 57, "Crash 2", "Bow" },
        { 52, "Crash 2", "Edge" },
        { 96, "Crash 2", "Bell" },
        { 27, "Crash 3", "Bow" },
        { 28, "Crash 3", "Edge" },
        { 31, "Crash 4", "Edge" },
        { 33, "Crash 5", "Edge" },
    }, 4 },
    { "efnote_efnote_3", "EFNOTE 3", "EFNOTE", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 41, "Tom 4", "Head" },
        { 39, "Tom 4", "Rim" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 22, "HH Edge", "Closed" },
        { 26, "HH Edge", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 59, "Ride", "Edge" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
        { 54, "Crash 1", "Bell" },
        { 57, "Crash 2", "Bow" },
        { 52, "Crash 2", "Edge" },
        { 56, "Crash 2", "Bell" },
        { 27, "Crash 3", "Bow" },
        { 28, "Crash 3", "Edge" },
    }, 4 },
    { "efnote_efnote_5", "EFNOTE 5", "EFNOTE", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 41, "Tom 4", "Head" },
        { 39, "Tom 4", "Rim" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 22, "HH Edge", "Closed" },
        { 26, "HH Edge", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 59, "Ride", "Edge" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
        { 54, "Crash 1", "Bell" },
        { 57, "Crash 2", "Bow" },
        { 52, "Crash 2", "Edge" },
        { 56, "Crash 2", "Bell" },
        { 27, "Crash 3", "Bow" },
        { 28, "Crash 3", "Edge" },
    }, 4 },
    { "efnote_efnote_7", "EFNOTE 7", "EFNOTE", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 41, "Tom 4", "Head" },
        { 39, "Tom 4", "Rim" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 22, "HH Edge", "Closed" },
        { 26, "HH Edge", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 59, "Ride", "Edge" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
        { 54, "Crash 1", "Bell" },
        { 57, "Crash 2", "Bow" },
        { 52, "Crash 2", "Edge" },
        { 56, "Crash 2", "Bell" },
        { 27, "Crash 3", "Bow" },
        { 28, "Crash 3", "Edge" },
    }, 4 },
    { "kat_kt_1", "KT-1", "KAT", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 48, "Tom 1", "Head" },
        { 45, "Tom 2", "Head" },
        { 43, "Tom 3", "Head" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 51, "Ride", "Bow" },
        { 49, "Crash 1", "Edge" },
        { 57, "Crash 2", "Edge" },
    }, 3 },
    { "kat_kt_2", "KT-2", "KAT", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 41, "Tom 4", "Head" },
        { 39, "Tom 4", "Rim" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 23, "Hi-Hat", "Half Open" },
        { 44, "HH Pedal", "Chick" },
        { 21, "HH Pedal", "Splash" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Edge" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
        { 57, "Crash 2", "Bow" },
        { 52, "Crash 2", "Edge" },
    }, 4 },
    { "kat_kt_3", "KT-3", "KAT", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 41, "Tom 4", "Head" },
        { 39, "Tom 4", "Rim" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 23, "Hi-Hat", "Half Open" },
        { 44, "HH Pedal", "Chick" },
        { 21, "HH Pedal", "Splash" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Edge" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
        { 57, "Crash 2", "Bow" },
        { 52, "Crash 2", "Edge" },
    }, 4 },
    { "kat_kt_4", "KT-4", "KAT", {
        { 36, "Kick", "Head" },
        { 35, "Kick 2", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 41, "Tom 4", "Head" },
        { 39, "Tom 4", "Rim" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 22, "HH Edge", "Closed" },
        { 26, "HH Edge", "Open" },
        { 85, "HH Bell", "Closed" },
        { 84, "HH Bell", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 21, "HH Pedal", "Splash" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 59, "Ride", "Edge" },
        { 49, "Crash 1", "Bow" },
        { 82, "Crash 1", "Bell" },
        { 55, "Crash 1", "Edge" },
        { 57, "Crash 2", "Bow" },
        { 83, "Crash 2", "Bell" },
        { 52, "Crash 2", "Edge" },
    }, 4 },
    { "medeli_dd40x", "DD40X", "Medeli", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 48, "Tom 1", "Head" },
        { 45, "Tom 2", "Head" },
        { 43, "Tom 3", "Head" },
        { 46, "Hi-Hat", "Open" },
        { 42, "Hi-Hat", "Closed" },
        { 44, "HH Pedal", "Chick" },
        { 51, "Ride", "Bow" },
        { 49, "Crash 1", "Edge" },
    }, 3 },
    { "medeli_dd50x", "DD50X", "Medeli", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 23, "Hi-Hat", "Half Open" },
        { 22, "HH Edge", "Closed" },
        { 26, "HH Edge", "Open" },
        { 24, "HH Edge", "Half Open" },
        { 44, "HH Pedal", "Chick" },
        { 21, "HH Pedal", "Splash" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 59, "Ride", "Edge" },
        { 49, "Crash 1", "Edge" },
        { 57, "Crash 2", "Edge" },
    }, 4 },
    { "medeli_dd512", "DD512", "Medeli", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 41, "Tom 4", "Head" },
        { 39, "Tom 4", "Rim" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 23, "Hi-Hat", "Half Open" },
        { 44, "HH Pedal", "Chick" },
        { 21, "HH Pedal", "Splash" },
        { 51, "Ride", "Bow" },
        { 49, "Crash 1", "Edge" },
        { 57, "Crash 2", "Edge" },
    }, 4 },
    { "medeli_dd514", "DD514", "Medeli", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 41, "Tom 4", "Head" },
        { 39, "Tom 4", "Rim" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 23, "Hi-Hat", "Half Open" },
        { 44, "HH Pedal", "Chick" },
        { 21, "HH Pedal", "Splash" },
        { 51, "Ride", "Bow" },
        { 49, "Crash 1", "Edge" },
        { 57, "Crash 2", "Edge" },
    }, 4 },
    { "medeli_dd516", "DD516", "Medeli", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 41, "Tom 4", "Head" },
        { 39, "Tom 4", "Rim" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 23, "Hi-Hat", "Half Open" },
        { 44, "HH Pedal", "Chick" },
        { 21, "HH Pedal", "Splash" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Edge" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
        { 57, "Crash 2", "Bow" },
        { 52, "Crash 2", "Edge" },
    }, 4 },
    { "medeli_dd518", "DD518", "Medeli", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 41, "Tom 4", "Head" },
        { 39, "Tom 4", "Rim" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 23, "Hi-Hat", "Half Open" },
        { 22, "HH Edge", "Closed" },
        { 26, "HH Edge", "Open" },
        { 24, "HH Edge", "Half Open" },
        { 44, "HH Pedal", "Chick" },
        { 21, "HH Pedal", "Splash" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 59, "Ride", "Edge" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
        { 57, "Crash 2", "Bow" },
        { 52, "Crash 2", "Edge" },
    }, 4 },
    { "medeli_dd522", "DD522", "Medeli", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 21, "HH Pedal", "Splash" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Edge" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
        { 57, "Crash 2", "Bow" },
        { 52, "Crash 2", "Edge" },
    }, 4 },
    { "medeli_dd60x", "DD60X", "Medeli", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 48, "Tom 1", "Head" },
        { 45, "Tom 2", "Head" },
        { 43, "Tom 3", "Head" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 21, "HH Pedal", "Splash" },
        { 51, "Ride", "Bow" },
        { 49, "Crash 1", "Edge" },
        { 57, "Crash 2", "Edge" },
    }, 4 },
    { "medeli_dd610", "DD610", "Medeli", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 48, "Tom 1", "Head" },
        { 45, "Tom 2", "Head" },
        { 43, "Tom 3", "Head" },
        { 41, "Tom 4", "Head" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 21, "HH Pedal", "Splash" },
        { 51, "Ride", "Bow" },
        { 49, "Crash 1", "Edge" },
        { 57, "Crash 2", "Edge" },
    }, 4 },
    { "medeli_dd620", "DD620", "Medeli", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 48, "Tom 1", "Head" },
        { 45, "Tom 2", "Head" },
        { 43, "Tom 3", "Head" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 21, "HH Pedal", "Splash" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 59, "Ride", "Edge" },
        { 49, "Crash 1", "Edge" },
        { 57, "Crash 2", "Edge" },
    }, 4 },
    { "medeli_dd630", "DD630", "Medeli", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 48, "Tom 1", "Head" },
        { 45, "Tom 2", "Head" },
        { 43, "Tom 3", "Head" },
        { 41, "Tom 4", "Head" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 21, "HH Pedal", "Splash" },
        { 51, "Ride", "Bow" },
        { 49, "Crash 1", "Edge" },
        { 57, "Crash 2", "Edge" },
    }, 4 },
    { "medeli_dd635", "DD635", "Medeli", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 41, "Tom 4", "Head" },
        { 39, "Tom 4", "Rim" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 22, "HH Edge", "Closed" },
        { 26, "HH Edge", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 21, "HH Pedal", "Splash" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 59, "Ride", "Edge" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
        { 57, "Crash 2", "Bow" },
        { 52, "Crash 2", "Edge" },
    }, 4 },
    { "medeli_dd638", "DD638", "Medeli", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 41, "Tom 4", "Head" },
        { 39, "Tom 4", "Rim" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 22, "HH Edge", "Closed" },
        { 26, "HH Edge", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 21, "HH Pedal", "Splash" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 59, "Ride", "Edge" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
        { 57, "Crash 2", "Bow" },
        { 52, "Crash 2", "Edge" },
    }, 4 },
    { "medeli_dd650", "DD650", "Medeli", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 41, "Tom 4", "Head" },
        { 39, "Tom 4", "Rim" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 22, "HH Edge", "Closed" },
        { 26, "HH Edge", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 21, "HH Pedal", "Splash" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 59, "Ride", "Edge" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
        { 57, "Crash 2", "Bow" },
        { 52, "Crash 2", "Edge" },
    }, 4 },
    { "millenium_mps_150", "MPS-150", "Millenium", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 48, "Tom 1", "Head" },
        { 45, "Tom 2", "Head" },
        { 43, "Tom 3", "Head" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 51, "Ride", "Bow" },
        { 49, "Crash 1", "Edge" },
    }, 3 },
    { "millenium_mps_250", "MPS-250", "Millenium", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 37, "Snare", "X-Stick" },
        { 48, "Tom 1", "Head" },
        { 45, "Tom 2", "Head" },
        { 41, "Tom 3", "Head" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 51, "Ride", "Bow" },
        { 55, "Crash 1", "Edge" },
    }, 3 },
    { "millenium_mps_450", "MPS-450", "Millenium", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 23, "Hi-Hat", "Half Open" },
        { 44, "HH Pedal", "Chick" },
        { 21, "HH Pedal", "Splash" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 59, "Ride", "Edge" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
    }, 4 },
    { "millenium_mps_500", "MPS-500", "Millenium", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 23, "Hi-Hat", "Half Open" },
        { 44, "HH Pedal", "Chick" },
        { 21, "HH Pedal", "Splash" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 59, "Ride", "Edge" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
    }, 4 },
    { "millenium_mps_600", "MPS-600", "Millenium", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 41, "Tom 4", "Head" },
        { 39, "Tom 4", "Rim" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 23, "Hi-Hat", "Half Open" },
        { 22, "HH Edge", "Closed" },
        { 26, "HH Edge", "Open" },
        { 24, "HH Edge", "Half Open" },
        { 44, "HH Pedal", "Chick" },
        { 21, "HH Pedal", "Splash" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 59, "Ride", "Edge" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
        { 57, "Crash 2", "Bow" },
        { 52, "Crash 2", "Edge" },
    }, 4 },
    { "millenium_mps_750", "MPS-750", "Millenium", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 41, "Tom 4", "Head" },
        { 39, "Tom 4", "Rim" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 23, "Hi-Hat", "Half Open" },
        { 22, "HH Edge", "Closed" },
        { 26, "HH Edge", "Open" },
        { 24, "HH Edge", "Half Open" },
        { 44, "HH Pedal", "Chick" },
        { 21, "HH Pedal", "Splash" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 59, "Ride", "Edge" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
        { 57, "Crash 2", "Bow" },
        { 52, "Crash 2", "Edge" },
    }, 4 },
    { "millenium_mps_850", "MPS-850", "Millenium", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 41, "Tom 4", "Head" },
        { 39, "Tom 4", "Rim" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 23, "Hi-Hat", "Half Open" },
        { 22, "HH Edge", "Closed" },
        { 26, "HH Edge", "Open" },
        { 24, "HH Edge", "Half Open" },
        { 44, "HH Pedal", "Chick" },
        { 21, "HH Pedal", "Splash" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 59, "Ride", "Edge" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
        { 57, "Crash 2", "Bow" },
        { 52, "Crash 2", "Edge" },
    }, 4 },
    { "millenium_mps_1000", "MPS-1000", "Millenium", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 41, "Tom 4", "Head" },
        { 39, "Tom 4", "Rim" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 22, "HH Edge", "Closed" },
        { 26, "HH Edge", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 21, "HH Pedal", "Splash" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 59, "Ride", "Edge" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
        { 57, "Crash 2", "Bow" },
        { 52, "Crash 2", "Edge" },
    }, 4 },
    { "pearl_e_merge", "e/MERGE", "Pearl", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 60, "Tom 1", "Head" },
        { 59, "Tom 1", "Rim" },
        { 58, "Tom 1", "Rim FX" },
        { 53, "Tom 2", "Head" },
        { 55, "Tom 2", "Rim" },
        { 54, "Tom 2", "Rim FX" },
        { 48, "Tom 3", "Head" },
        { 50, "Tom 3", "Rim" },
        { 49, "Tom 3", "Rim FX" },
        { 43, "Tom 4", "Head" },
        { 45, "Tom 4", "Rim" },
        { 44, "Tom 4", "Rim FX" },
        { 66, "Hi-Hat", "Closed" },
        { 68, "Hi-Hat", "Open" },
        { 65, "HH Edge", "Closed" },
        { 67, "HH Edge", "Open" },
        { 64, "HH Pedal", "Chick" },
        { 63, "HH Pedal", "Splash" },
        { 72, "Ride", "Bow" },
        { 73, "Ride", "Bell" },
        { 74, "Ride", "Edge" },
        { 81, "Crash 1", "Bow" },
        { 79, "Crash 1", "Edge" },
        { 83, "Crash 2", "Bow" },
        { 84, "Crash 2", "Edge" },
    }, 4 },
    { "pearl_mimic_pro", "Mimic Pro", "Pearl", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 60, "Tom 1", "Head" },
        { 59, "Tom 1", "Rim" },
        { 58, "Tom 1", "Rim FX" },
        { 53, "Tom 2", "Head" },
        { 55, "Tom 2", "Rim" },
        { 54, "Tom 2", "Rim FX" },
        { 48, "Tom 3", "Head" },
        { 50, "Tom 3", "Rim" },
        { 49, "Tom 3", "Rim FX" },
        { 43, "Tom 4", "Head" },
        { 45, "Tom 4", "Rim" },
        { 44, "Tom 4", "Rim FX" },
        { 66, "Hi-Hat", "Closed" },
        { 68, "Hi-Hat", "Open" },
        { 65, "HH Edge", "Closed" },
        { 67, "HH Edge", "Open" },
        { 64, "HH Pedal", "Chick" },
        { 63, "HH Pedal", "Splash" },
        { 72, "Ride", "Bow" },
        { 73, "Ride", "Bell" },
        { 74, "Ride", "Edge" },
        { 81, "Crash 1", "Bow" },
        { 79, "Crash 1", "Edge" },
        { 83, "Crash 2", "Bow" },
        { 84, "Crash 2", "Edge" },
    }, 4 },
    { "roland_hd_1", "HD-1", "Roland", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 48, "Tom 1", "Head" },
        { 45, "Tom 2", "Head" },
        { 43, "Tom 3", "Head" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 51, "Ride", "Bow" },
        { 49, "Crash 1", "Bow" },
    }, 3 },
    { "roland_hd_3", "HD-3", "Roland", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 48, "Tom 1", "Head" },
        { 45, "Tom 2", "Head" },
        { 43, "Tom 3", "Head" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 22, "HH Edge", "Closed" },
        { 26, "HH Edge", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Edge" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
    }, 4 },
    { "roland_spd_30", "SPD-30", "Roland", {
        { 64, "Kick", "Head" },
        { 65, "Snare", "Head" },
        { 66, "Tom 1", "Head" },
        { 67, "Tom 3", "Head" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 60, "Hi-Hat", "Half Open" },
        { 22, "HH Edge", "Closed" },
        { 26, "HH Edge", "Open" },
        { 61, "HH Edge", "Half Open" },
        { 62, "Ride", "Bow" },
        { 63, "Crash 1", "Edge" },
    }, 3 },
    { "roland_spd_sx", "SPD-SX", "Roland", {
        { 66, "Kick", "Head" },
        { 67, "Snare", "Head" },
        { 72, "Snare", "Rimshot" },
        { 63, "Tom 1", "Head" },
        { 64, "Tom 2", "Head" },
        { 68, "Tom 3", "Head" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 60, "Hi-Hat", "Half Open" },
        { 22, "HH Edge", "Closed" },
        { 26, "HH Edge", "Open" },
        { 61, "HH Edge", "Half Open" },
        { 62, "Ride", "Bow" },
        { 65, "Crash 1", "Edge" },
    }, 4 },
    { "roland_spd_sx_pro", "SPD-SX PRO", "Roland", {
        { 66, "Kick", "Head" },
        { 67, "Snare", "Head" },
        { 72, "Snare", "Rimshot" },
        { 63, "Tom 1", "Head" },
        { 64, "Tom 2", "Head" },
        { 68, "Tom 3", "Head" },
        { 60, "Hi-Hat", "Closed" },
        { 61, "Hi-Hat", "Open" },
        { 74, "HH Edge", "Closed" },
        { 44, "HH Pedal", "Chick" },
        { 62, "Ride", "Bow" },
        { 76, "Ride", "Edge" },
        { 65, "Crash 1", "Edge" },
    }, 4 },
    { "roland_td_1", "TD-1", "Roland", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 48, "Tom 1", "Head" },
        { 45, "Tom 2", "Head" },
        { 41, "Tom 3", "Head" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 22, "HH Edge", "Closed" },
        { 26, "HH Edge", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Edge" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
        { 57, "Crash 2", "Bow" },
        { 52, "Crash 2", "Edge" },
    }, 4 },
    { "roland_td_02", "TD-02", "Roland", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 48, "Tom 1", "Head" },
        { 45, "Tom 2", "Head" },
        { 43, "Tom 3", "Head" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 22, "HH Edge", "Closed" },
        { 26, "HH Edge", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 59, "Ride", "Edge" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
        { 57, "Crash 2", "Bow" },
        { 52, "Crash 2", "Edge" },
    }, 4 },
    { "roland_td_3", "TD-3", "Roland", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 48, "Tom 1", "Head" },
        { 45, "Tom 2", "Head" },
        { 41, "Tom 3", "Head" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 22, "HH Edge", "Closed" },
        { 26, "HH Edge", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Edge" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
        { 57, "Crash 2", "Bow" },
        { 52, "Crash 2", "Edge" },
    }, 4 },
    { "roland_td_4", "TD-4", "Roland", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 48, "Tom 1", "Head" },
        { 45, "Tom 2", "Head" },
        { 41, "Tom 3", "Head" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 22, "HH Edge", "Closed" },
        { 26, "HH Edge", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Edge" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
        { 57, "Crash 2", "Bow" },
        { 52, "Crash 2", "Edge" },
    }, 4 },
    { "roland_td_6", "TD-6", "Roland", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 50, "Tom 1", "Head" },
        { 45, "Tom 2", "Head" },
        { 41, "Tom 3", "Head" },
        { 31, "Tom 4", "Head" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 22, "HH Edge", "Closed" },
        { 26, "HH Edge", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Edge" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
        { 57, "Crash 2", "Bow" },
        { 52, "Crash 2", "Edge" },
    }, 4 },
    { "roland_td_07", "TD-07", "Roland", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 48, "Tom 1", "Head" },
        { 45, "Tom 2", "Head" },
        { 43, "Tom 3", "Head" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 22, "HH Edge", "Closed" },
        { 26, "HH Edge", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 59, "Ride", "Edge" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
        { 57, "Crash 2", "Bow" },
        { 52, "Crash 2", "Edge" },
    }, 4 },
    { "roland_td_8", "TD-8", "Roland", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 41, "Tom 3", "Head" },
        { 43, "Tom 3", "Rim" },
        { 31, "Tom 4", "Head" },
        { 32, "Tom 4", "Rim" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 22, "HH Edge", "Closed" },
        { 26, "HH Edge", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Edge" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
        { 57, "Crash 2", "Bow" },
        { 52, "Crash 2", "Edge" },
    }, 4 },
    { "roland_td_9", "TD-9", "Roland", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 41, "Tom 4", "Head" },
        { 39, "Tom 4", "Rim" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 22, "HH Edge", "Closed" },
        { 26, "HH Edge", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Edge" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
        { 57, "Crash 2", "Bow" },
        { 52, "Crash 2", "Edge" },
        { 31, "Crash 3", "Bow" },
        { 32, "Crash 3", "Edge" },
    }, 4 },
    { "roland_td_10", "TD-10", "Roland", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 41, "Tom 4", "Head" },
        { 39, "Tom 4", "Rim" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 22, "HH Edge", "Closed" },
        { 26, "HH Edge", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Edge" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
        { 57, "Crash 2", "Bow" },
        { 52, "Crash 2", "Edge" },
        { 31, "Crash 3", "Bow" },
        { 32, "Crash 3", "Edge" },
        { 33, "Crash 4", "Bow" },
        { 34, "Crash 4", "Edge" },
    }, 4 },
    { "roland_td_10_tdw_1", "TD-10 + TDW-1", "Roland", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 41, "Tom 4", "Head" },
        { 39, "Tom 4", "Rim" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 22, "HH Edge", "Closed" },
        { 26, "HH Edge", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 59, "Ride", "Edge" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
        { 57, "Crash 2", "Bow" },
        { 52, "Crash 2", "Edge" },
        { 31, "Crash 3", "Bow" },
        { 32, "Crash 3", "Edge" },
        { 33, "Crash 4", "Bow" },
        { 34, "Crash 4", "Edge" },
    }, 4 },
    { "roland_td_11", "TD-11", "Roland", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 22, "HH Edge", "Closed" },
        { 26, "HH Edge", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 59, "Ride", "Edge" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
        { 57, "Crash 2", "Bow" },
        { 52, "Crash 2", "Edge" },
    }, 4 },
    { "roland_td_12", "TD-12", "Roland", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 37, "Snare", "X-Stick" },
        { 40, "Snare", "Rimshot" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 29, "Tom 4", "Head" },
        { 30, "Tom 4", "Rim" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 22, "HH Edge", "Closed" },
        { 26, "HH Edge", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 59, "Ride", "Edge" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
        { 57, "Crash 2", "Bow" },
        { 52, "Crash 2", "Edge" },
        { 27, "Crash 3", "Bow" },
        { 28, "Crash 3", "Edge" },
    }, 4 },
    { "roland_td_15", "TD-15", "Roland", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 22, "HH Edge", "Closed" },
        { 26, "HH Edge", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 59, "Ride", "Edge" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
        { 57, "Crash 2", "Bow" },
        { 52, "Crash 2", "Edge" },
        { 27, "Crash 3", "Bow" },
        { 28, "Crash 3", "Edge" },
    }, 4 },
    { "roland_td_17", "TD-17", "Roland", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 41, "Tom 4", "Head" },
        { 39, "Tom 4", "Rim" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 22, "HH Edge", "Closed" },
        { 26, "HH Edge", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 59, "Ride", "Edge" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
        { 57, "Crash 2", "Bow" },
        { 52, "Crash 2", "Edge" },
        { 27, "Crash 3", "Bow" },
        { 28, "Crash 3", "Edge" },
        { 29, "Crash 4", "Bow" },
        { 30, "Crash 4", "Edge" },
    }, 4 },
    { "roland_td_20", "TD-20", "Roland", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 41, "Tom 4", "Head" },
        { 39, "Tom 4", "Rim" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 22, "HH Edge", "Closed" },
        { 26, "HH Edge", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 59, "Ride", "Edge" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
        { 57, "Crash 2", "Bow" },
        { 52, "Crash 2", "Edge" },
        { 27, "Crash 3", "Bow" },
        { 28, "Crash 3", "Edge" },
        { 29, "Crash 4", "Bow" },
        { 30, "Crash 4", "Edge" },
        { 31, "Crash 5", "Bow" },
        { 32, "Crash 5", "Edge" },
    }, 4 },
    { "roland_td_25", "TD-25", "Roland", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 22, "HH Edge", "Closed" },
        { 26, "HH Edge", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 59, "Ride", "Edge" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
        { 57, "Crash 2", "Bow" },
        { 52, "Crash 2", "Edge" },
        { 27, "Crash 3", "Bow" },
        { 28, "Crash 3", "Edge" },
    }, 4 },
    { "roland_td_27", "TD-27", "Roland", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 41, "Tom 4", "Head" },
        { 39, "Tom 4", "Rim" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 22, "HH Edge", "Closed" },
        { 26, "HH Edge", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 59, "Ride", "Edge" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
        { 57, "Crash 2", "Bow" },
        { 52, "Crash 2", "Edge" },
        { 27, "Crash 3", "Bow" },
        { 28, "Crash 3", "Edge" },
        { 29, "Crash 4", "Bow" },
        { 30, "Crash 4", "Edge" },
        { 31, "Crash 5", "Bow" },
        { 32, "Crash 5", "Edge" },
    }, 4 },
    { "roland_td_30", "TD-30", "Roland", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 41, "Tom 4", "Head" },
        { 39, "Tom 4", "Rim" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 22, "HH Edge", "Closed" },
        { 26, "HH Edge", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 59, "Ride", "Edge" },
        { 25, "Ride", "Mute" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
        { 57, "Crash 2", "Bow" },
        { 52, "Crash 2", "Edge" },
        { 27, "Crash 3", "Bow" },
        { 28, "Crash 3", "Edge" },
        { 29, "Crash 4", "Bow" },
        { 30, "Crash 4", "Edge" },
        { 31, "Crash 5", "Bow" },
        { 32, "Crash 5", "Edge" },
    }, 4 },
    { "roland_td_50", "TD-50", "Roland", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 41, "Tom 4", "Head" },
        { 39, "Tom 4", "Rim" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 22, "HH Edge", "Closed" },
        { 26, "HH Edge", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 59, "Ride", "Edge" },
        { 25, "Ride", "Mute" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
        { 57, "Crash 2", "Bow" },
        { 52, "Crash 2", "Edge" },
        { 27, "Crash 3", "Bow" },
        { 28, "Crash 3", "Edge" },
        { 29, "Crash 4", "Bow" },
        { 30, "Crash 4", "Edge" },
        { 31, "Crash 5", "Bow" },
        { 32, "Crash 5", "Edge" },
    }, 4 },
    { "roland_td_50x", "TD-50X", "Roland", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 41, "Tom 4", "Head" },
        { 39, "Tom 4", "Rim" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 22, "HH Edge", "Closed" },
        { 26, "HH Edge", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 59, "Ride", "Edge" },
        { 25, "Ride", "Mute" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
        { 57, "Crash 2", "Bow" },
        { 52, "Crash 2", "Edge" },
        { 27, "Crash 3", "Bow" },
        { 28, "Crash 3", "Edge" },
        { 29, "Crash 4", "Bow" },
        { 30, "Crash 4", "Edge" },
        { 31, "Crash 5", "Bow" },
        { 32, "Crash 5", "Edge" },
    }, 4 },
    { "roland_tm_2", "TM-2", "Roland", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
    }, 3 },
    { "roland_v71", "V71", "Roland", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 41, "Tom 4", "Head" },
        { 39, "Tom 4", "Rim" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 22, "HH Edge", "Closed" },
        { 26, "HH Edge", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 59, "Ride", "Edge" },
        { 25, "Ride", "Mute" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
        { 57, "Crash 2", "Bow" },
        { 52, "Crash 2", "Edge" },
        { 27, "Crash 3", "Bow" },
        { 28, "Crash 3", "Edge" },
        { 29, "Crash 4", "Bow" },
        { 30, "Crash 4", "Edge" },
        { 31, "Crash 5", "Bow" },
        { 32, "Crash 5", "Edge" },
    }, 4 },
    { "simmons_sd200", "SD200", "Simmons", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 48, "Tom 1", "Head" },
        { 45, "Tom 2", "Head" },
        { 43, "Tom 3", "Head" },
        { 41, "Tom 4", "Head" },
        { 42, "Hi-Hat", "Closed" },
        { 44, "HH Pedal", "Chick" },
    }, 3 },
    { "simmons_sd350", "SD350", "Simmons", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 48, "Tom 1", "Head" },
        { 45, "Tom 2", "Head" },
        { 43, "Tom 3", "Head" },
        { 41, "Tom 4", "Head" },
        { 42, "Hi-Hat", "Closed" },
        { 44, "HH Pedal", "Chick" },
    }, 3 },
    { "simmons_sd550", "SD550", "Simmons", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 48, "Tom 1", "Head" },
        { 45, "Tom 2", "Head" },
        { 43, "Tom 3", "Head" },
        { 41, "Tom 4", "Head" },
        { 42, "Hi-Hat", "Closed" },
        { 44, "HH Pedal", "Chick" },
    }, 3 },
    { "simmons_sd600", "SD600", "Simmons", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 41, "Tom 4", "Head" },
        { 39, "Tom 4", "Rim" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 85, "HH Pedal", "Splash" },
    }, 4 },
    { "simmons_sd1200", "SD1200", "Simmons", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 41, "Tom 4", "Head" },
        { 39, "Tom 4", "Rim" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 86, "Hi-Hat", "Half Open" },
        { 22, "HH Edge", "Closed" },
        { 26, "HH Edge", "Open" },
        { 24, "HH Edge", "Half Open" },
        { 44, "HH Pedal", "Chick" },
        { 85, "HH Pedal", "Splash" },
        { 49, "Crash 1", "Bow" },
        { 52, "Crash 2", "Edge" },
        { 55, "Crash 1", "Edge" },
        { 57, "Crash 2", "Bow" },
    }, 4 },
    { "simmons_sd2000", "SD2000", "Simmons", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 41, "Tom 4", "Head" },
        { 39, "Tom 4", "Rim" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 86, "Hi-Hat", "Half Open" },
        { 22, "HH Edge", "Closed" },
        { 26, "HH Edge", "Open" },
        { 24, "HH Edge", "Half Open" },
        { 44, "HH Pedal", "Chick" },
        { 85, "HH Pedal", "Splash" },
        { 49, "Crash 1", "Bow" },
        { 52, "Crash 2", "Edge" },
        { 55, "Crash 1", "Edge" },
        { 57, "Crash 2", "Bow" },
    }, 4 },
    { "simmons_titan_70", "Titan 70", "Simmons", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 41, "Tom 4", "Head" },
        { 39, "Tom 4", "Rim" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 59, "Ride", "Edge" },
        { 49, "Crash 1", "Edge" },
        { 57, "Crash 2", "Edge" },
    }, 4 },
    { "yamaha_dtx4_series", "DTX4 Series", "Yamaha", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 48, "Tom 1", "Head" },
        { 47, "Tom 2", "Head" },
        { 43, "Tom 3", "Head" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "HH Edge", "Closed" },
        { 44, "HH Pedal", "Chick" },
        { 51, "Ride", "Bow" },
        { 49, "Crash 1", "Bow" },
    }, 3 },
    { "yamaha_dtx5_series", "DTX5 Series", "Yamaha", {
        { 36, "Kick", "Head" },
        { 57, "Kick 2", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 48, "Tom 1", "Head" },
        { 47, "Tom 2", "Head" },
        { 43, "Tom 3", "Head" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 78, "HH Edge", "Closed" },
        { 79, "HH Edge", "Open" },
        { 85, "HH Bell", "Closed" },
        { 86, "HH Bell", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 83, "HH Pedal", "Splash" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 52, "Ride", "Edge" },
        { 59, "Crash 1", "Bow" },
        { 55, "Crash 1", "Bell" },
        { 49, "Crash 1", "Edge" },
    }, 4 },
    { "yamaha_dtx6_series", "DTX6 Series", "Yamaha", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 48, "Tom 1", "Head" },
        { 14, "Tom 1", "Rim" },
        { 15, "Tom 1", "Rim FX" },
        { 47, "Tom 2", "Head" },
        { 18, "Tom 2", "Rim" },
        { 19, "Tom 2", "Rim FX" },
        { 43, "Tom 3", "Head" },
        { 20, "Tom 3", "Rim" },
        { 23, "Tom 3", "Rim FX" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 78, "HH Edge", "Closed" },
        { 79, "HH Edge", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 83, "HH Pedal", "Splash" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 52, "Ride", "Edge" },
        { 59, "Crash 1", "Bow" },
        { 55, "Crash 1", "Bell" },
        { 49, "Crash 1", "Edge" },
        { 17, "Crash 2", "Bow" },
        { 16, "Crash 2", "Bell" },
        { 57, "Crash 2", "Edge" },
        { 26, "Crash 3", "Bow" },
        { 29, "Crash 3", "Bell" },
        { 28, "Crash 3", "Edge" },
    }, 4 },
    { "yamaha_dtx7_series", "DTX7 Series", "Yamaha", {
        { 36, "Kick", "Head" },
        { 35, "Kick 2", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 48, "Tom 1", "Head" },
        { 14, "Tom 1", "Rim" },
        { 15, "Tom 1", "Rim FX" },
        { 47, "Tom 2", "Head" },
        { 18, "Tom 2", "Rim" },
        { 19, "Tom 2", "Rim FX" },
        { 43, "Tom 3", "Head" },
        { 20, "Tom 3", "Rim" },
        { 23, "Tom 3", "Rim FX" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 78, "HH Edge", "Closed" },
        { 79, "HH Edge", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 83, "HH Pedal", "Splash" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 52, "Ride", "Edge" },
        { 59, "Crash 1", "Bow" },
        { 55, "Crash 1", "Bell" },
        { 49, "Crash 1", "Edge" },
        { 17, "Crash 2", "Bow" },
        { 16, "Crash 2", "Bell" },
        { 57, "Crash 2", "Edge" },
        { 26, "Crash 3", "Bow" },
        { 29, "Crash 3", "Bell" },
        { 28, "Crash 3", "Edge" },
    }, 4 },
    { "yamaha_dtx8_series", "DTX8 Series", "Yamaha", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 48, "Tom 1", "Head" },
        { 14, "Tom 1", "Rim" },
        { 15, "Tom 1", "Rim FX" },
        { 47, "Tom 2", "Head" },
        { 18, "Tom 2", "Rim" },
        { 19, "Tom 2", "Rim FX" },
        { 43, "Tom 3", "Head" },
        { 20, "Tom 3", "Rim" },
        { 23, "Tom 3", "Rim FX" },
        { 41, "Tom 4", "Head" },
        { 24, "Tom 4", "Rim" },
        { 25, "Tom 4", "Rim FX" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 78, "HH Edge", "Closed" },
        { 79, "HH Edge", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 83, "HH Pedal", "Splash" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 52, "Ride", "Edge" },
        { 59, "Crash 1", "Bow" },
        { 55, "Crash 1", "Bell" },
        { 49, "Crash 1", "Edge" },
        { 17, "Crash 2", "Bow" },
        { 16, "Crash 2", "Bell" },
        { 57, "Crash 2", "Edge" },
        { 26, "Crash 3", "Bow" },
        { 29, "Crash 3", "Bell" },
        { 28, "Crash 3", "Edge" },
        { 56, "Crash 4", "Bow" },
        { 68, "Crash 4", "Bell" },
        { 67, "Crash 4", "Edge" },
    }, 4 },
    { "yamaha_dtx9_series", "DTX9 Series", "Yamaha", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 48, "Tom 1", "Head" },
        { 14, "Tom 1", "Rim" },
        { 15, "Tom 1", "Rim FX" },
        { 47, "Tom 2", "Head" },
        { 18, "Tom 2", "Rim" },
        { 19, "Tom 2", "Rim FX" },
        { 43, "Tom 3", "Head" },
        { 20, "Tom 3", "Rim" },
        { 23, "Tom 3", "Rim FX" },
        { 41, "Tom 4", "Head" },
        { 24, "Tom 4", "Rim" },
        { 25, "Tom 4", "Rim FX" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 78, "HH Edge", "Closed" },
        { 79, "HH Edge", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 83, "HH Pedal", "Splash" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 52, "Ride", "Edge" },
        { 59, "Crash 1", "Bow" },
        { 55, "Crash 1", "Bell" },
        { 49, "Crash 1", "Edge" },
        { 17, "Crash 2", "Bow" },
        { 16, "Crash 2", "Bell" },
        { 57, "Crash 2", "Edge" },
        { 26, "Crash 3", "Bow" },
        { 29, "Crash 3", "Bell" },
        { 28, "Crash 3", "Edge" },
        { 56, "Crash 4", "Bow" },
        { 68, "Crash 4", "Bell" },
        { 67, "Crash 4", "Edge" },
    }, 4 },
    { "yamaha_dtx10_series", "DTX10 Series", "Yamaha", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 48, "Tom 1", "Head" },
        { 14, "Tom 1", "Rim" },
        { 15, "Tom 1", "Rim FX" },
        { 47, "Tom 2", "Head" },
        { 18, "Tom 2", "Rim" },
        { 19, "Tom 2", "Rim FX" },
        { 43, "Tom 3", "Head" },
        { 20, "Tom 3", "Rim" },
        { 23, "Tom 3", "Rim FX" },
        { 41, "Tom 4", "Head" },
        { 24, "Tom 4", "Rim" },
        { 25, "Tom 4", "Rim FX" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 78, "HH Edge", "Closed" },
        { 79, "HH Edge", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 83, "HH Pedal", "Splash" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 52, "Ride", "Edge" },
        { 59, "Crash 1", "Bow" },
        { 55, "Crash 1", "Bell" },
        { 49, "Crash 1", "Edge" },
        { 17, "Crash 2", "Bow" },
        { 16, "Crash 2", "Bell" },
        { 57, "Crash 2", "Edge" },
        { 26, "Crash 3", "Bow" },
        { 29, "Crash 3", "Bell" },
        { 28, "Crash 3", "Edge" },
        { 56, "Crash 4", "Bow" },
        { 68, "Crash 4", "Bell" },
        { 67, "Crash 4", "Edge" },
    }, 4 },
    { "yamaha_dtxplorer", "DTXplorer", "Yamaha", {
        { 33, "Kick", "Head" },
        { 31, "Snare", "Head" },
        { 34, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 48, "Tom 1", "Head" },
        { 47, "Tom 2", "Head" },
        { 43, "Tom 3", "Head" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 85, "HH Pedal", "Splash" },
        { 51, "Ride", "Bow" },
        { 52, "Ride", "Edge" },
        { 49, "Crash 1", "Bow" },
        { 57, "Crash 1", "Edge" },
        { 91, "Crash 2", "Bow" },
        { 55, "Crash 2", "Edge" },
    }, 4 },
    { "yamaha_dtxpress", "DTXpress", "Yamaha", {
        { 36, "Kick", "Head" },
        { 85, "Kick 2", "Head" },
        { 38, "Snare", "Head" },
        { 34, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 48, "Tom 1", "Head" },
        { 54, "Tom 1", "Rim" },
        { 47, "Tom 2", "Head" },
        { 56, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 52, "Tom 3", "Rim" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 93, "HH Edge", "Closed" },
        { 92, "HH Edge", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 59, "Ride", "Edge" },
        { 49, "Crash 1", "Edge" },
        { 55, "Crash 2", "Edge" },
        { 90, "Crash 3", "Edge" },
    }, 4 },
    { "yamaha_dtx_pro", "DTX-PRO", "Yamaha", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 48, "Tom 1", "Head" },
        { 14, "Tom 1", "Rim" },
        { 15, "Tom 1", "Rim FX" },
        { 47, "Tom 2", "Head" },
        { 18, "Tom 2", "Rim" },
        { 19, "Tom 2", "Rim FX" },
        { 43, "Tom 3", "Head" },
        { 20, "Tom 3", "Rim" },
        { 23, "Tom 3", "Rim FX" },
        { 41, "Tom 4", "Head" },
        { 24, "Tom 4", "Rim" },
        { 25, "Tom 4", "Rim FX" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 78, "HH Edge", "Closed" },
        { 79, "HH Edge", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 83, "HH Pedal", "Splash" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 52, "Ride", "Edge" },
        { 59, "Crash 1", "Bow" },
        { 55, "Crash 1", "Bell" },
        { 49, "Crash 1", "Edge" },
        { 17, "Crash 2", "Bow" },
        { 16, "Crash 2", "Bell" },
        { 57, "Crash 2", "Edge" },
        { 26, "Crash 3", "Bow" },
        { 29, "Crash 3", "Bell" },
        { 28, "Crash 3", "Edge" },
        { 56, "Crash 4", "Bow" },
        { 68, "Crash 4", "Bell" },
        { 67, "Crash 4", "Edge" },
        { 65, "Crash 5", "Bow" },
        { 58, "Crash 5", "Bell" },
        { 54, "Crash 5", "Edge" },
    }, 4 },
    { "yamaha_dtx_prox", "DTX-PROX", "Yamaha", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 48, "Tom 1", "Head" },
        { 14, "Tom 1", "Rim" },
        { 15, "Tom 1", "Rim FX" },
        { 47, "Tom 2", "Head" },
        { 18, "Tom 2", "Rim" },
        { 19, "Tom 2", "Rim FX" },
        { 43, "Tom 3", "Head" },
        { 20, "Tom 3", "Rim" },
        { 23, "Tom 3", "Rim FX" },
        { 41, "Tom 4", "Head" },
        { 24, "Tom 4", "Rim" },
        { 25, "Tom 4", "Rim FX" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 78, "HH Edge", "Closed" },
        { 79, "HH Edge", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 83, "HH Pedal", "Splash" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 52, "Ride", "Edge" },
        { 59, "Crash 1", "Bow" },
        { 55, "Crash 1", "Bell" },
        { 49, "Crash 1", "Edge" },
        { 17, "Crash 2", "Bow" },
        { 16, "Crash 2", "Bell" },
        { 57, "Crash 2", "Edge" },
        { 26, "Crash 3", "Bow" },
        { 29, "Crash 3", "Bell" },
        { 28, "Crash 3", "Edge" },
        { 56, "Crash 4", "Bow" },
        { 68, "Crash 4", "Bell" },
        { 67, "Crash 4", "Edge" },
        { 65, "Crash 5", "Bow" },
        { 58, "Crash 5", "Bell" },
        { 54, "Crash 5", "Edge" },
    }, 4 },
    { "zildjian_alchem_e", "ALCHEM-E", "Zildjian", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 84, "Tom 1", "Rim FX" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 85, "Tom 2", "Rim FX" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 86, "Tom 3", "Rim FX" },
        { 41, "Tom 4", "Head" },
        { 39, "Tom 4", "Rim" },
        { 87, "Tom 4", "Rim FX" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 22, "HH Edge", "Closed" },
        { 26, "HH Edge", "Open" },
        { 27, "HH Pedal", "Chick" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 59, "Ride", "Edge" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
        { 89, "Crash 1", "Bell" },
        { 57, "Crash 2", "Bow" },
        { 52, "Crash 2", "Edge" },
        { 91, "Crash 2", "Bell" },
        { 80, "Crash 3", "Bow" },
        { 81, "Crash 3", "Edge" },
        { 82, "Crash 3", "Bell" },
        { 92, "Crash 4", "Bow" },
        { 94, "Crash 4", "Edge" },
        { 95, "Crash 4", "Bell" },
    }, 4 },
    { "others_aerodrums", "Aerodrums", "Others", {
        { 36, "Kick", "Head" },
        { 35, "Kick 2", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 48, "Tom 1", "Head" },
        { 47, "Tom 2", "Head" },
        { 43, "Tom 3", "Head" },
        { 41, "Tom 4", "Head" },
        { 46, "Hi-Hat", "Closed" },
        { 27, "Hi-Hat", "Open" },
        { 26, "HH Edge", "Closed" },
        { 28, "HH Edge", "Open" },
        { 29, "HH Pedal", "Chick" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 49, "Crash 1", "Edge" },
        { 57, "Crash 2", "Edge" },
    }, 4 },
    { "others_adrums", "aDrums", "Others", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 48, "Tom 1", "Head" },
        { 45, "Tom 2", "Head" },
        { 43, "Tom 3", "Head" },
        { 46, "Hi-Hat", "Closed" },
        { 26, "HH Edge", "Closed" },
        { 44, "HH Pedal", "Chick" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 59, "Ride", "Edge" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
        { 57, "Crash 2", "Bow" },
        { 52, "Crash 2", "Edge" },
    }, 4 },
    { "others_druml_s1", "DruML S1", "Others", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 41, "Tom 4", "Head" },
        { 39, "Tom 4", "Rim" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 22, "HH Edge", "Closed" },
        { 26, "HH Edge", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 59, "Ride", "Edge" },
        { 25, "Ride", "Mute" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
        { 57, "Crash 2", "Bow" },
        { 52, "Crash 2", "Edge" },
        { 27, "Crash 3", "Bow" },
        { 28, "Crash 3", "Edge" },
        { 29, "Crash 4", "Bow" },
        { 30, "Crash 4", "Edge" },
        { 31, "Crash 5", "Bow" },
        { 32, "Crash 5", "Edge" },
    }, 4 },
    { "others_gewa", "GEWA", "Others", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 41, "Tom 4", "Head" },
        { 39, "Tom 4", "Rim" },
        { 42, "Hi-Hat", "Closed" },
        { 46, "Hi-Hat", "Open" },
        { 26, "HH Edge", "Closed" },
        { 19, "HH Bell", "Closed" },
        { 44, "HH Pedal", "Chick" },
        { 21, "HH Pedal", "Splash" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 59, "Ride", "Edge" },
        { 49, "Crash 1", "Bow" },
        { 55, "Crash 1", "Edge" },
        { 17, "Crash 1", "Bell" },
        { 57, "Crash 2", "Bow" },
        { 52, "Crash 2", "Edge" },
        { 18, "Crash 2", "Bell" },
        { 88, "Crash 3", "Bow" },
        { 89, "Crash 3", "Edge" },
        { 22, "Crash 3", "Bell" },
        { 90, "Crash 4", "Bow" },
        { 91, "Crash 4", "Edge" },
        { 23, "Crash 4", "Bell" },
        { 92, "Crash 5", "Bow" },
        { 93, "Crash 5", "Edge" },
        { 24, "Crash 5", "Bell" },
    }, 4 },
    { "others_nfuzd", "NFuZD", "Others", {
        { 36, "Kick", "Head" },
        { 38, "Snare", "Head" },
        { 40, "Snare", "Rimshot" },
        { 37, "Snare", "X-Stick" },
        { 48, "Tom 1", "Head" },
        { 50, "Tom 1", "Rim" },
        { 45, "Tom 2", "Head" },
        { 47, "Tom 2", "Rim" },
        { 43, "Tom 3", "Head" },
        { 58, "Tom 3", "Rim" },
        { 41, "Tom 4", "Head" },
        { 39, "Tom 4", "Rim" },
        { 42, "Hi-Hat", "Closed" },
        { 22, "HH Edge", "Closed" },
        { 26, "HH Edge", "Open" },
        { 44, "HH Pedal", "Chick" },
        { 21, "HH Pedal", "Splash" },
        { 51, "Ride", "Bow" },
        { 53, "Ride", "Bell" },
        { 59, "Ride", "Edge" },
        { 49, "Crash 1", "Bow" },
        { 62, "Crash 1", "Bell" },
        { 55, "Crash 1", "Edge" },
        { 57, "Crash 2", "Bow" },
        { 64, "Crash 2", "Bell" },
        { 52, "Crash 2", "Edge" },
        { 14, "Perc 1", "Hit" },
        { 15, "Perc 2", "Hit" },
    }, 4 },
    };
}

const std::vector<DrumKitDefinition>& DrumKitLibrary::getAllKits()
{
    static auto kits = buildAllKits();
    return kits;
}

const DrumKitDefinition* DrumKitLibrary::findKit (const juce::String& id)
{
    auto& kits = getAllKits();
    for (auto& kit : kits)
        if (kit.id == id)
            return &kit;
    return nullptr;
}

const DrumKitDefinition& DrumKitLibrary::getDefaultKit()
{
    static const juce::String defaultId = "generic_controller_generic_no_cc";
    auto* kit = findKit (defaultId);
    if (kit != nullptr)
        return *kit;
    return getAllKits().front();
}

std::vector<juce::String> DrumKitLibrary::getManufacturers()
{
    auto& kits = getAllKits();
    std::vector<juce::String> result;
    for (auto& kit : kits)
    {
        if (std::find (result.begin(), result.end(), kit.manufacturer) == result.end())
            result.push_back (kit.manufacturer);
    }
    return result;
}

std::vector<const DrumKitDefinition*> DrumKitLibrary::getKitsByManufacturer (const juce::String& mfr)
{
    auto& kits = getAllKits();
    std::vector<const DrumKitDefinition*> result;
    for (auto& kit : kits)
        if (kit.manufacturer == mfr)
            result.push_back (&kit);
    return result;
}
